---
version: "3.2"

services:
  jenkins:
    image: 127.0.0.1:5000/jenkins
    ports:
      - "8070:8080"
      - "50000:50000"
    volumes:
      - /mnt/data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
